# Dependencies
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            trueSKY Documentation
tagline:          ''
description:      ''
url:              http://docs.simul.co
baseurl:          /

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          2.1.0

array: []